// src/data/products.js
const baseUrl = 'https://search.rakuten.co.jp/search/mall/';
// DBから取得するダミーデータ
// このデータに購入済みかというフラグを追加する予定
const products = {
  food: [
    { id: 1, name: '水', quantity: '17L', url: `${baseUrl}水` },
    { id: 2, name: 'レトルトご飯', quantity: '17食', url: `${baseUrl}レトルトご飯` },
    { id: 3, name: 'レトルト食品', quantity: '6個', url: `${baseUrl}レトルト食品` },
    { id: 4, name: '缶詰(さばの味噌煮、野菜など)', quantity: '6缶', url: `${baseUrl}缶詰(さばの味噌煮、野菜など)` },
    { id: 5, name: '栄養補助食品', quantity: '6箱', url: `${baseUrl}栄養補助食品` },
    { id: 6, name: '野菜ジュース', quantity: '6本', url: `${baseUrl}野菜ジュース` },
    { id: 7, name: 'チーズ・プロテインバー等', quantity: '2パック', url: `${baseUrl}チーズ・プロテインバー等` },
    { id: 8, name: '健康飲料粉末', quantity: '6袋', url: `${baseUrl}健康飲料粉末` },
    { id: 9, name: '調味料セット', quantity: '適宜', url: `${baseUrl}調味料セット` },
    { id: 10, name: '乾麺 即席麺', quantity: '7パック', url: `${baseUrl}乾麺 即席麺` },
    { id: 11, name: '無洗米', quantity: '3kg', url: `${baseUrl}無洗米` },
    { id: 12, name: '飲み物', quantity: '6本', url: `${baseUrl}飲み物` },
    { id: 13, name: 'お菓子', quantity: '7パック', url: `${baseUrl}お菓子` },
    { id: 14, name: '果物の缶詰', quantity: '7缶', url: `${baseUrl}果物の缶詰` },
    { id: 15, name: '乾物', quantity: '適量', url: `${baseUrl}乾物` },
    { id: 16, name: 'フリーズドライ食品', quantity: '適量', url: `${baseUrl}フリーズドライ食品` },
  ],
  hygiene: [
    { id: 17, name: '除菌ウェットティッシュ', quantity: '70枚', url: `${baseUrl}除菌ウェットティッシュ` },
    { id: 18, name: 'アルコールスプレー', quantity: '1本', url: `${baseUrl}アルコールスプレー` },
    { id: 19, name: 'マスク', quantity: '7枚', url: `${baseUrl}マスク` },
    { id: 20, name: '口内洗浄液', quantity: '630ml', url: `${baseUrl}口内洗浄液` },
    { id: 21, name: '救急箱', quantity: '1箱', url: `${baseUrl}救急箱` },
    { id: 22, name: '常備薬', quantity: '1箱', url: `${baseUrl}常備薬` },
    { id: 23, name: '使い捨てコンタクトレンズ', quantity: '1人1か月分', url: `${baseUrl}使い捨てコンタクトレンズ` },
    { id: 24, name: '携帯トイレ・簡易トイレ', quantity: '35回分', url: `${baseUrl}携帯トイレ・簡易トイレ` },
    { id: 25, name: '歯みがき用ウェットティッシュ', quantity: '70枚程度', url: `${baseUrl}歯みがき用ウェットティッシュ` },
    { id: 26, name: 'ウェットボディタオル', quantity: '7枚', url: `${baseUrl}ウェットボディタオル` },
  ],
  daily: [
    { id: 27, name: 'カセットコンロ', quantity: '1台', url: `${baseUrl}カセットコンロ` },
    { id: 28, name: 'カセットボンベ', quantity: 'ガスコンロ1台につき1日4/3本', url: `${baseUrl}カセットボンベ` },
    { id: 29, name: 'ラップ', quantity: '1本', url: `${baseUrl}ラップ` },
    { id: 30, name: 'ポリ袋', quantity: '1箱', url: `${baseUrl}ポリ袋` },
    { id: 31, name: 'ビニール手袋', quantity: '1箱', url: `${baseUrl}ビニール手袋` },
    { id: 32, name: 'アルミホイル', quantity: '1本', url: `${baseUrl}アルミホイル` },
    { id: 33, name: 'トイレットペーパー', quantity: '3ロール', url: `${baseUrl}トイレットペーパー` },
    { id: 34, name: 'ティッシュペーパー', quantity: '3箱', url: `${baseUrl}ティッシュペーパー` },
    { id: 35, name: '懐中電灯', quantity: '1灯', url: `${baseUrl}懐中電灯` },
    { id: 36, name: '乾電池', quantity: '単1～単4までのセット', url: `${baseUrl}乾電池` },
    { id: 37, name: '点火棒', quantity: '1本', url: `${baseUrl}点火棒` },
    { id: 38, name: '使い捨てカイロ', quantity: '14個', url: `${baseUrl}使い捨てカイロ` },
    { id: 39, name: '携帯電話 充電器', quantity: '携帯台数に合わせて用意', url: `${baseUrl}携帯電話 充電器` },
    { id: 40, name: '布製ガムテープ', quantity: '2巻', url: `${baseUrl}布製ガムテープ` },
    { id: 41, name: '軍手', quantity: '7組', url: `${baseUrl}軍手` },
    { id: 42, name: '新聞紙', quantity: '適宜', url: `${baseUrl}新聞紙` },
    { id: 43, name: '手回し充電式などのラジオ', quantity: '1台', url: `${baseUrl}手回し充電式などのラジオ` },
    { id: 44, name: 'マルチツール', quantity: '1個', url: `${baseUrl}マルチツール` },
    { id: 45, name: '給水袋', quantity: '1袋', url: `${baseUrl}給水袋` },
    { id: 46, name: 'ポータブルストーブ', quantity: '1台', url: `${baseUrl}ポータブルストーブ` },
    { id: 47, name: 'LEDランタン', quantity: '最低3台', url: `${baseUrl}LEDランタン` },
    { id: 48, name: 'ヘッドライト', quantity: '1個', url: `${baseUrl}ヘッドライト` },
    { id: 49, name: 'クーラーボックス', quantity: '1個', url: `${baseUrl}クーラーボックス` },
    { id: 50, name: 'リュックサック', quantity: '1個', url: `${baseUrl}リュックサック` },
  ],
};

export default products;
